---
# for use when mysql AND server are running in the same docker container
spring:
  datasource:
    username: "${DB_USER:user}"
    password: "${DB_PASSWORD:password}"
    url: "jdbc:mysql://db/kitties"
    jdbc-url: "jdbc:mysql://db/kitties"

  flyway:
    user: "${DB_USER:user}"
    password: "${DB_PASSWORD:password}"
    url: "jdbc:mysql://db/kitties"

...
